### ISSUE TITLE
Is there a guide on how to install it?

### ISSUE THREAD

**Issue by MysticFragilist** [SquidDev-CC/CC-Images#3]
I just started out using computercraft and find it amazing! great job on the library. My question, is pretty much the title, is there a specific way of installing this library? or do I simply copy your code on a pastebin and I download it from there?

**Comment by SquidDev** [comment]
This project is a bit of a mishmash of various things, rather than one project.

Assuming you're referring to the bitmap parser, which is what the README refers to, `pastebin get Y3JeZWzV ImagesAPI` is the way to go - [see the forum thread](https://www.computercraft.info/forums2/index.php?/topic/19044-bitmap-images/).

**Comment by MysticFragilist** [comment]
Yes that was what I was referring to. Thanks a lot!
